version: '3.1'

services:
  raft_1:
    image: raft-test:latest
    hostname: raft_1
    environment:
      - NODES=node2,node3
      - ADDRESSES=raft_2:2222,raft_3:2223
      - PORT=2221
      - ID=1
      - IDS=2,3
    volumes:
      - './node_1_data:/node_data'
    mem_limit: 1000m

  raft_2:
    image: raft-test:latest
    hostname: raft_2
    environment:
      - NODES=node1,node3
      - ADDRESSES=raft_1:2221,raft_3:2223
      - PORT=2222
      - ID=2
      - IDS=1,3
    volumes:
      - './node_2_data:/node_data'
    mem_limit: 1000m

  raft_3:
    image: raft-test:latest
    hostname: raft_3
    environment:
      - NODES=node1,node2
      - ADDRESSES=raft_1:2221,raft_2:2222
      - PORT=2223
      - ID=3
      - IDS=1,2
    volumes:
      - './node_3_data:/node_data'
    mem_limit: 1000m

networks:
  raftnet:
    driver: bridge